#include <ctype.h>

const unsigned char _ctype[0x80] =
{
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL | _C_SPACE | _C_BLANK),
  (_C_CNTRL | _C_SPACE),
  (_C_CNTRL | _C_SPACE),
  (_C_CNTRL | _C_SPACE),
  (_C_CNTRL | _C_SPACE),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_CNTRL),
  (_C_SPACE | _C_BLANK),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_DIGIT | _C_XDIGIT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_UPPER | _C_XDIGIT),
  (_C_UPPER | _C_XDIGIT),
  (_C_UPPER | _C_XDIGIT),
  (_C_UPPER | _C_XDIGIT),
  (_C_UPPER | _C_XDIGIT),
  (_C_UPPER | _C_XDIGIT),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_UPPER),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_LOWER | _C_XDIGIT),
  (_C_LOWER | _C_XDIGIT),
  (_C_LOWER | _C_XDIGIT),
  (_C_LOWER | _C_XDIGIT),
  (_C_LOWER | _C_XDIGIT),
  (_C_LOWER | _C_XDIGIT),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_LOWER),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_PUNCT),
  (_C_CNTRL),
};

int tolower(int c)
{
  if (isupper(c)) c += 'a' - 'A';
  return c;
}

int toupper(int c)
{
  if (islower(c)) c -= 'a' - 'A';
  return c;
}

